version: '2'
 
services:
  app:
    restart: always
    build:
      context:  ./app
      dockerfile: Dockerfile
    expose:
      - "8080"
    volumes:
      - /usr/src/app/sql
  proxy:
    restart: always
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    links:
      - app
    volumes_from:
      - app
